# library(github)
# library(devtools)
# library(roxygen2)
setwd("/Users/Aron/Dropbox/Thesis/3-Variance/Journal/Computational Analysis/compute/")
# library(github)
# library(rgithub, lib.loc = "/Users/Aron/github/local/")
library(httpuv)
library(jsonlite)
library(dplyr)
library(plyr)
library(stringr)
library(igraph)
library(mallet)
library(LDAvis)
library(wordcloud)